print("твоя программа первая строка")
print("lictpu was here 29.09")
print("murphyqwek was here 29.09")
print('бельков вячеслав')
print("добавка от форма lictpu")
print("Могильный Борислав")
print("Истомина Полина")
print('Виктор Фрик, 142')
print('Аверин Владимир')
print('Гонгин вос тхере 29.09')
